# Generated by Django 2.1.4 on 2019-01-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('vendor', models.BooleanField(default=False)),
                ('phone_Number', models.CharField(blank=True, max_length=124)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('city', models.CharField(blank=True, max_length=1024)),
                ('zip_Code', models.CharField(blank=True, max_length=12)),
                ('hours', models.CharField(blank=True, help_text='Hours of Operation', max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Point of Contact', max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
