# Generated by Django 2.1.4 on 2018-12-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='randomText',
            field=models.TextField(default=''),
        ),
    ]
