# Generated by Django 2.1.4 on 2018-12-31 20:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181231_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='randomText',
        ),
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(default='Address line 2', max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default='ZIP / Postal code', max_length=12),
        ),
    ]
