# Generated by Django 2.1.4 on 2018-12-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181231_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phone_Number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zip_code',
            new_name='zip_Code',
        ),
    ]
