# Generated by Django 2.1.4 on 2019-01-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Address Line 1', max_length=1024),
        ),
    ]
