# Generated by Django 2.1.4 on 2019-01-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190102_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, help_text='Point of Contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hours',
            field=models.CharField(blank=True, help_text='Hours of Operation', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_Code',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
