# Generated by Django 2.1.4 on 2019-01-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190102_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
