# Generated by Django 2.1.4 on 2018-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Describe the Item Here', max_length=200)),
                ('expiry', models.CharField(default='Enter expiration date', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved by another user'), ('RESTOCKING', 'Item may be stocked soon')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(default='Any misc info about your item', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Describe the Item Here', max_length=200)),
                ('expiry', models.CharField(default='Enter expiration date', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved by another user'), ('RESTOCKING', 'Item may be stocked soon')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(default='Any misc info about your item', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Describe the Item Here', max_length=200)),
                ('expiry', models.CharField(default='Enter expiration date', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved by another user'), ('RESTOCKING', 'Item may be stocked soon')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(default='Any misc info about your item', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
