# Generated by Django 2.1.4 on 2019-01-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe your donation here', max_length=200)),
                ('expiry', models.CharField(help_text='Enter expiration date here', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(help_text='Miscellaneous info about your donation', max_length=50)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe your donation here', max_length=200)),
                ('expiry', models.CharField(help_text='Enter expiration date here', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(help_text='Miscellaneous info about your donation', max_length=50)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiscObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe your donation here', max_length=200)),
                ('expiry', models.CharField(help_text='Enter expiration date here', max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10)),
                ('misc', models.CharField(help_text='Miscellaneous info about your donation', max_length=50)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
