# Generated by Django 2.1.4 on 2018-12-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='foods',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='miscobjects',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
