# Generated by Django 2.1.4 on 2018-12-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181231_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='user',
        ),
        migrations.RemoveField(
            model_name='miscobjects',
            name='user',
        ),
        migrations.AddField(
            model_name='drinks',
            name='donator',
            field=models.CharField(blank=True, default='Enter your username for verification', max_length=50),
        ),
        migrations.AddField(
            model_name='foods',
            name='donator',
            field=models.CharField(blank=True, default='Enter your username for verification', max_length=50),
        ),
        migrations.AddField(
            model_name='miscobjects',
            name='donator',
            field=models.CharField(blank=True, default='Enter your username for verification', max_length=50),
        ),
    ]
