# Generated by Django 2.1.4 on 2019-01-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190107_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date', max_length=200),
        ),
        migrations.AlterField(
            model_name='foods',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date', max_length=200),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date', max_length=200),
        ),
    ]
