# Generated by Django 2.1.4 on 2019-01-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190101_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='description',
            field=models.CharField(help_text='Describe your donation here', max_length=200),
        ),
        migrations.AlterField(
            model_name='foods',
            name='description',
            field=models.CharField(help_text='Describe your donation here', max_length=200),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='description',
            field=models.CharField(help_text='Describe your donation here', max_length=200),
        ),
    ]
