# Generated by Django 2.1.4 on 2019-01-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190107_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='expiry',
            field=models.DateField(help_text='Enter expiration date'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='expiry',
            field=models.DateField(help_text='Enter expiration date'),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='expiry',
            field=models.DateField(help_text='Enter expiration date'),
        ),
    ]
