# Generated by Django 2.1.4 on 2019-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190103_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='donator',
            field=models.CharField(help_text='Enter your username', max_length=50),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date here', max_length=200),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='misc',
            field=models.CharField(help_text='Miscellaneous info about your donation', max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='donator',
            field=models.CharField(help_text='Enter your username', max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date here', max_length=200),
        ),
        migrations.AlterField(
            model_name='foods',
            name='misc',
            field=models.CharField(help_text='Miscellaneous info about your donation', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='donator',
            field=models.CharField(help_text='Enter your username', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='expiry',
            field=models.CharField(help_text='Enter expiration date here', max_length=200),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='misc',
            field=models.CharField(help_text='Miscellaneous info about your donation', max_length=50),
        ),
    ]
