# Generated by Django 2.1.4 on 2019-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20190103_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='donator',
            field=models.CharField(default='enter username', max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='donator',
            field=models.CharField(default='enter username', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='donator',
            field=models.CharField(default='enter username', max_length=50),
        ),
    ]
