# Generated by Django 2.1.4 on 2019-01-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190103_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='donator',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='donator',
        ),
        migrations.RemoveField(
            model_name='miscobjects',
            name='donator',
        ),
        migrations.AddField(
            model_name='drinks',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000166A03E0F98>', max_length=50),
        ),
        migrations.AddField(
            model_name='foods',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000166A03E0F98>', max_length=50),
        ),
        migrations.AddField(
            model_name='miscobjects',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000166A03E0F98>', max_length=50),
        ),
    ]
