# Generated by Django 2.1.4 on 2019-01-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190103_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002A21694DF98>', max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002A21694DF98>', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000002A21694DF98>', max_length=50),
        ),
    ]
