# Generated by Django 2.1.4 on 2019-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190103_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000020D4F6C0EF0>', max_length=50),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='foods',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000020D4F6C0EF0>', max_length=50),
        ),
        migrations.AlterField(
            model_name='foods',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='donatorID',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000020D4F6C0EF0>', max_length=50),
        ),
        migrations.AlterField(
            model_name='miscobjects',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be picked up'), ('RESERVED', 'Item reserved')], default='AVAILABLE', max_length=10),
        ),
    ]
