# Generated by Django 2.1.4 on 2019-01-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20190103_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='donatorID',
            new_name='donator',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='donatorID',
            new_name='donator',
        ),
        migrations.RenameField(
            model_name='miscobjects',
            old_name='donatorID',
            new_name='donator',
        ),
    ]
